### ISSUE TITLE
Tool not opening on latest stable 23h2 W11

### ISSUE THREAD

**Issue by fernbacher** [meetrevision/revision-tool#76]
**Describe the bug**
The tool opens in task manager/process explorer as expected, but it hangs with conhost as the issue it looks like, i thought about changing the font on CMD as it might have hanged on that but it didn't work

**To Reproduce**
1. Go to 'Desktop'
2. Click on 'Revision Tool'
3. Scroll down to 'Nothing'

**Expected behavior**
It should open, it used to open on the version before this one of windows, i am currently on 22631.3155 windows 11 stable, last time i was on the version before this, the tool worked

**Screenshots**
![image](https://github.com/meetrevision/revision-tool/assets/66071319/ee7d2ce4-b078-40ef-a14a-63859c10e755)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 22631.3155
 - Playbook Version: ReviOS 23.12
 - Revision Tool Version: 1.8.1

**Comment by fernbacher** [comment]
Update: 1.8.0 tool works properly, the 1.8.1 does not open, i've just tested.

**Comment by irkella** [comment]
Can also confirm that 1.8.1 will not open on Windows 11 Pro 23H2. No issues with 1.8.0.

**Comment by melo936** [comment]
conhost has nothing to do with the problem. It appears, because we added a CLI support in recent versions.

Since the ReviOS 23.12 release, we have decided to integrate a custom system package for removing system components, and Revision Tool 1.8.1 now checks if the ReviOS package is available in the packages list. I assume you are not using a playbook from the meetrevision/playbook release page, and it is a custom one or directly git cloned then zipped as an apbx file which won't work. The system package gets build by GitHub Actions whenever we publish a new release, therefore, you must fork the repo, add your own TOKEN and create a new release to build the playbook correctly.

In order to fix it, simply reapply the latest playbook from the meetrevision/playbook releases page.

**Comment by irkella** [comment]
> conhost has nothing to do with the problem. It appears, because we added a CLI support in recent versions.
> 
> Since the ReviOS 23.12 release, we have decided to integrate a custom system package for removing system components, and Revision Tool 1.8.1 now checks if the ReviOS package is available in the packages list. I assume you are not using a playbook from the meetrevision/playbook release page, and it is a custom one or directly git cloned then zipped as an apbx file which won't work. The system package gets build by GitHub Actions whenever we publish a new release, therefore, you must fork the repo, add your own TOKEN and create a new release to build the playbook correctly.
> 
> In order to fix it, simply reapply the latest playbook from the meetrevision/playbook releases page.

I am on ReviOS 23.12, directly from meetrevision/playbook.

**Comment by melo936** [comment]
> I am on ReviOS 23.12, directly from meetrevision/playbook.

Could you reapply [this](https://github.com/melo936/playbook/releases/tag/24.02.01
)?

**Comment by melo936** [comment]
Fixed by [1.8.2](https://github.com/meetrevision/revision-tool/releases/tag/1.8.2)
